services:
  mediamtx:
    image: bluenviron/mediamtx:1.20.1
    ports:
      - "8554:8554"
      - "9999:8888"
      - "1935:1935"
    restart: unless-stopped

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    user: "${UID:-1000}:${GID:-1000}"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    depends_on:
      - mediamtx
